name: povray
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- numpy=1.11.0=py27_1
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.1=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.1=np111py27_0
- setuptools=20.7.0=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - certifi==2016.2.28
  - configparser==3.3.0.post2
  - correlation==0.0.1
  - dask==0.8.1
  - decorator==4.0.9
  - django==1.9.6
  - entrypoints==0.2.1
  - euclid==0.0.1
  - functools32==3.2.3.post2
  - image==1.5.3
  - imagemat==0.0.1
  - ipykernel==4.3.1
  - ipython==4.2.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.1.4
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - markupsafe==0.23
  - mistune==0.7.2
  - mosek==7.1.49
  - nbconvert==4.2.0
  - nbformat==4.0.1
  - notebook==4.2.0
  - pathlib2==2.1.0
  - pexpect==4.0.1
  - pickleshare==0.7.2
  - pillow==3.2.0
  - projection==0.0.1
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pymworks==2.0.1
  - pyzmq==15.2.0
  - qtconsole==4.2.1
  - roibuddy==1.0.0
  - sima==1.3.0
  - simplegeneric==0.8.1
  - singledispatch==3.4.0.3
  - spread==0.0.1
  - terminado==0.6
  - tornado==4.3
  - tqdm==4.7.0
  - traitlets==4.2.1
  - widgetsnbextension==1.2.2

